---
- hosts: localhost
  vars:
    - project_name: localgovdrupal
    - project_type: drupal8
    - webroot: web
    - build_type: local
    - _env_type: dev
    # Path to your project root.
    - deploy_path: /home/ce-dev/deploy/live.local
    # This actually does not take any backup, but is needed to populate settings.php.
    - mysql_backup:
        handling: none
        credentials_handling: static
    # A list of Drupal sites (for multisites).
    - drupal:
        sites:
          - folder: "default"
            public_files: "sites/default/files"
            install_command: "-y si localgov_microsites"
            # Toggle config import on/off. Disabled for initial passes.
            config_import_command: ""
            # config_import_command: "cim"
            config_sync_directory: "config/sync"
            sanitize_command: "sql-sanitize"
            # Remove after initial pass, to avoid reinstalling Drupal.
            force_install: true
            base_url: "https://{{ _domain_name }}"
    # Composer command to run.
    - composer:
        command: install
        no_dev: false
        working_dir: "{{ deploy_path }}"
        apcu_autoloader: false
    - drush:
        use_vendor: true
    - drush_bin: ../../../vendor/drush/drush/drush
  pre_tasks:
    - name: Download composer file.
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/drupal/recommended-project/9.5.x/composer.json
        dest: "{{ deploy_path }}/composer.json"
        force: false
    - name: Enable composer-patches plugin.
      ansible.builtin.command:
        cmd: composer config --no-plugins allow-plugins.cweagans/composer-patches true
        chdir: "{{ deploy_path }}"
    - name: Install drush.
      ansible.builtin.command:
        cmd: composer require drush/drush:11.*
        chdir: "{{ deploy_path }}"
    - name: Install LocalGov Drupal Microsites.
      ansible.builtin.command:
        cmd: composer require localgovdrupal/localgov_microsites
        chdir: "{{ deploy_path }}"
    - name: Add the CE repository.
      ansible.builtin.command:
        cmd: composer config repositories.codeenigma vcs https://github.com/codeenigma/ce_localgovdrupal_config
        chdir: "{{ deploy_path }}"
    - name: Install CE LocalGov Drupal Config.
      ansible.builtin.command:
        cmd: composer require codeenigma/ce_localgovdrupal_config
        chdir: "{{ deploy_path }}"
  roles:
    - _init # Sets some variables the deploy scripts rely on.
    - composer # Composer install step.
    - database_backup # This is still needed to generate credentials.
    - config_generate # Generates settings.php
    - database_apply # Run drush updb and config import.
    - _exit # Some common housekeeping.
  post_tasks:
    - name: Install Code Enigma tweaks to LocalGov Drupal.
      ansible.builtin.command:
        cmd: "{{ drush_bin }} -y en ce_localgovdrupal_config"
        chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ drupal.sites[0].folder }}"
      failed_when: false
